import { PortfolioView } from "@/components/portfolio/PortfolioView";
import { PortfolioData } from "@/lib/types";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Demo Portfolio | PortfolioHub",
    description: "See what a PortfolioHub portfolio looks like with this interactive demo.",
};

const demoData: PortfolioData = {
    profile: {
        username: "justinsaju",
        password_pin: "0000",
        full_name: "Justin Jacob Saju",
        tagline: "ECE Engineer | Embedded Systems · VLSI · IoT · AI-Accelerated Engineering",
        email: "justinsaju21@gmail.com",
        github: "justinsaju21",
        linkedin: "justinjacobsaju",
        bio: "I'm an Electronics & Communication Engineer at SRMIST, specializing in Digital IC Design, Embedded Systems, and IoT. I optimize hardware through Thermal Management and AI-Accelerated Verification, bridging the gap between physical silicon and intelligent software. Currently researching SoC Testing at NSYSU, Taiwan. Founder & Chair of IEEE MTT-S SRM Student Chapter.",
        degree: "B.Tech Electronics & Communication Engineering",
        university: "SRM Institute of Science and Technology",
        graduation_year: "2027",
        theme_preference: "modern",
        profile_image: "",
        resume_url: "https://docs.google.com/document/d/1oEAf4BAUeUv-QptuoNsQglzuAtBdF_AZ/edit",
        primary_color: "#6366f1",
        secondary_color: "#14b8a6",
        font_choice: "inter",
        card_style: "glass",
        animation_enabled: true,
        section_order: "about,skills,experience,projects,leadership,education,contact",
        section_visibility: "",
        custom_sections: "[]",
        bg_color: "#ffffff",
        surface_color: "#f8fafc",
        text_primary: "#0f172a",
        text_muted: "#475569",
        text_dim: "#94a3b8",
        heading_font: "Inter",
        body_font: "Inter",
        button_style: "solid",
        container_width: "normal",
        custom_css: "",
    },
    experiences: [
        {
            username: "justinsaju",
            title: "SoC Testing Researcher",
            company: "NSYSU University",
            location: "Taiwan",
            start_date: "Aug 2025",
            end_date: "Jan 2026",
            is_current: false,
            description_points: [
                "Researched System-on-Chip (SoC) testing methodologies focusing on Design for Testability (DFT)",
                "Implemented Automatic Test Pattern Generation (ATPG) for stuck-at fault coverage optimization",
                "Studied advanced SoC testing architectures including Scan Chains and Logic BIST",
                "Analyzed IEEE 1149.1 (JTAG) and IEEE 1500 testing standards for hardware verification",
            ],
            type: "internship",
        },
        {
            username: "justinsaju",
            title: "Data Science Intern",
            company: "Mannai Corporation",
            location: "Doha, Qatar",
            start_date: "2023",
            end_date: "2024",
            is_current: false,
            description_points: [
                "Developed interactive dashboards using Power BI for enterprise data visualization",
                "Explored Microsoft Azure cloud services and infrastructure for data analytics",
                "Applied data science principles to real-world business problems at scale",
                "Collaborated with enterprise teams on analytics solutions using Microsoft tools",
            ],
            type: "internship",
        },
        {
            username: "justinsaju",
            title: "Electronics Cooling Capstone",
            company: "Dell Technologies",
            location: "Chennai, India",
            start_date: "2024",
            end_date: "2024",
            is_current: false,
            description_points: [
                "Mastered ANSYS Icepak for component-level and system-level thermal simulation",
                "Analyzed Junction-to-Case and Case-to-Ambient thermal resistance for reliability",
                "Optimized heat sink geometries and fan airflow profiles for data centers",
                "Applied computational fluid dynamics to solve conjugate heat transfer problems",
            ],
            type: "job",
        },
        {
            username: "justinsaju",
            title: "Community Connect Programme",
            company: "Divyakaruniya Ashramam",
            location: "Kerala, India",
            start_date: "2024",
            end_date: "2024",
            is_current: false,
            description_points: [
                "Volunteered at Divyakaruniya Ashramam for the Community Connect initiative",
                "Contributed to community welfare programs and charitable activities",
                "Developed interpersonal and leadership skills through meaningful social work",
            ],
            type: "volunteer",
        },
    ],
    projects: [
        {
            username: "justinsaju",
            title: "Hybrid Approximate Multiplier",
            description: "Verilog implementation of hybrid approximate multiplier for low-power computing applications. Optimized for area and power efficiency in VLSI design with novel approximation techniques.",
            tech_stack: ["Verilog", "VLSI", "Low Power", "Research"],
            repo_url: "https://github.com/justinsaju21/Hybrid_Approximate_Multiplier",
            live_url: "",
            image_url: "",
            featured: true,
        },
        {
            username: "justinsaju",
            title: "CMOS Switch & Duality Visualizer",
            description: "Interactive web application for deep-dive visualization into Static CMOS Logic and CMOS Duality. Essential virtual lab tool for ECE students and educators.",
            tech_stack: ["Python", "Streamlit", "VLSI", "Education"],
            repo_url: "https://github.com/justinsaju21/CMOS-Switch-Translator-Duality-Conduction-Visualizer",
            live_url: "https://justinsaju21-cmos-switch-translator-duality-conducti-app-akx8f0.streamlit.app/",
            image_url: "",
            featured: true,
        },
        {
            username: "justinsaju",
            title: "LogicMap Pro",
            description: "Professional Karnaugh Map solver and visualizer. Simplifies Boolean algebra minimization for digital logic students with an intuitive, interactive interface.",
            tech_stack: ["Python", "Streamlit", "Digital Logic", "Education"],
            repo_url: "https://github.com/justinsaju21/logicmap-pro",
            live_url: "https://justinsaju21-logicmap-pro-app-kvmnf2.streamlit.app/",
            image_url: "",
            featured: true,
        },
        {
            username: "justinsaju",
            title: "Stick Diagram Painter",
            description: "Tool for creating VLSI stick diagrams for circuit layout visualization. Assists in understanding physical design rules and layout planning for IC designers.",
            tech_stack: ["Python", "VLSI", "Physical Design", "Visualization"],
            repo_url: "https://github.com/justinsaju21/stick-diagram-painter",
            live_url: "https://justinsaju21-stick-diagram-painter-1--home-uunyi2.streamlit.app/",
            image_url: "",
            featured: false,
        },
        {
            username: "justinsaju",
            title: "5x5x5 LED Matrix Display",
            description: "3D LED cube display with custom animations and patterns. Hardware project combining Arduino microcontrollers with creative LED programming.",
            tech_stack: ["C++", "Arduino", "LED Matrix", "Hardware"],
            repo_url: "https://github.com/justinsaju21/5x5x5_Led_Matrix_Display",
            live_url: "",
            image_url: "",
            featured: false,
        },
        {
            username: "justinsaju",
            title: "Photobooth Mailer",
            description: "Vintage-style web photobooth that captures photos via webcam and emails them directly to users. Perfect event utility with retro aesthetics.",
            tech_stack: ["Python", "Streamlit", "Email", "Camera"],
            repo_url: "https://github.com/justinsaju21/photobooth-mailer",
            live_url: "https://justinsaju21-photobooth-mailer-main-l2yfdj.streamlit.app/",
            image_url: "",
            featured: false,
        },
    ],
    skills: [
        {
            username: "justinsaju",
            category: "Embedded & Hardware",
            skills_list: ["Arduino", "ESP32", "Raspberry Pi", "PCB Design", "IoT Protocols", "Sensor Integration"],
        },
        {
            username: "justinsaju",
            category: "VLSI & IC Design",
            skills_list: ["Verilog", "SystemVerilog", "UVM", "DFT Testing", "Fault Modeling", "SoC Verification", "FPGA"],
        },
        {
            username: "justinsaju",
            category: "Data Science & AI",
            skills_list: ["Python", "Power BI", "Microsoft Azure", "Data Analytics", "Machine Learning", "Streamlit"],
        },
        {
            username: "justinsaju",
            category: "5G & Communications",
            skills_list: ["Network Slicing", "Wireshark", "Edge Computing", "RF Design", "Signal Processing"],
        },
        {
            username: "justinsaju",
            category: "Thermal Engineering",
            skills_list: ["ANSYS Icepak", "CFD Simulation", "Heat Sink Design", "Junction Temp Analysis"],
        },
    ],
    education: [
        {
            username: "justinsaju",
            degree: "B.Tech Electronics & Communication Engineering",
            field: "VLSI, Embedded Systems & IoT",
            institution: "SRM Institute of Science and Technology",
            year: "2027",
            is_current: true,
        },
    ],
    leadership: [
        {
            username: "justinsaju",
            title: "Founder & Chairperson",
            organization: "IEEE MTT-S SRM Student Branch Chapter",
            description: "Founded and lead the IEEE Microwave Theory & Technology Society student chapter at SRMIST, organizing technical workshops and industry connect sessions.",
            achievements: [
                "Established the chapter from scratch with 50+ active members",
                "Organized technical workshops on RF Design and 5G Communications",
                "Coordinated industry expert sessions and networking events",
            ],
            type: "club",
        },
        {
            username: "justinsaju",
            title: "Anti-Ragging Committee Representative",
            organization: "SRM Institute of Science and Technology",
            description: "Served as the student representative ensuring a safe and inclusive campus environment for all students.",
            achievements: [
                "Served as student voice in anti-ragging committee",
                "Helped maintain a safe environment for 300+ freshmen",
            ],
            type: "academic",
        },
        {
            username: "justinsaju",
            title: "Class Representative",
            organization: "SRM Institute of Science and Technology",
            description: "Elected class representative bridging communication between students and faculty.",
            achievements: [
                "Coordinated academic schedules and student concerns",
                "Liaised between student body and department faculty",
            ],
            type: "academic",
        },
        {
            username: "justinsaju",
            title: "TECHKNOW Hackathon — 1st Place",
            organization: "SRM Institute of Science and Technology",
            description: "Won first place at the TECHKNOW technical competition with an innovative hardware solution.",
            achievements: [
                "Competed against 80+ teams in a 24-hour hackathon",
                "Developed a hardware prototype that impressed the judging panel",
            ],
            type: "competition",
        },
        {
            username: "justinsaju",
            title: "Creative Ingenuity — 1st Place",
            organization: "National Level Competition",
            description: "Secured first place at the national-level Creative Ingenuity competition.",
            achievements: [
                "Won against participants from 30+ colleges across India",
                "Demonstrated exceptional problem-solving and creativity",
            ],
            type: "competition",
        },
        {
            username: "justinsaju",
            title: "AI Hackday — Round 2 Qualifier",
            organization: "National AI Competition",
            description: "Advanced to Round 2 of the national AI Hackday competition, demonstrating strong AI/ML skills.",
            achievements: [
                "Built an AI solution in a time-constrained environment",
                "Qualified for advanced rounds among top teams nationally",
            ],
            type: "competition",
        },
    ],
    customSections: [],
    sectionOrder: ["about", "skills", "experience", "projects", "leadership", "education", "contact"],
    hiddenSections: [],
};

export default function DemoPage() {
    return <PortfolioView data={demoData} />;
}
